# version: "3.8"

services:
  app1:
    build: .
    image: users-api
    environment:
      SERVER_NAME: app1

  app2:
    build: .
    image: users-api
    environment:
      SERVER_NAME: app2

  app3:
    build: .
    image: users-api
    environment:
      SERVER_NAME: app3

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
